export const endpoints = {
  auth: {
    login: '/auth/login',
    me: '/students/me',
  },
  courses: {
    list: '/courses',
    detail: (id: number) => `/courses/${id}`,
    lessons: (courseId: number) => `/lessons/course/${courseId}`,
    modules: (courseId: number) => `/courses/${courseId}/modules`,
    moduleDetail: (moduleId: number) => `/courses/modules/${moduleId}`,
    prerequisites: (courseId: number) => `/courses/${courseId}/prerequisites`,
  },
  learningPaths: {
    list: '/learning-paths',
    detail: (id: number) => `/learning-paths/${id}`,
    courses: (id: number) => `/learning-paths/${id}/courses`,
  },
  enrollments: {
    byStudent: (studentId: number) => `/enrollments/student/${studentId}`,
    create: '/enrollments',
  },
  progress: {
    me: '/progress/me',
    courses: '/progress/me/courses',
    update: (lessonId: number) => `/progress/${lessonId}`,
  },
  sessions: {
    me: '/sessions/me',
    history: '/sessions/me/history',
    create: '/sessions',
    voiceStart: '/sessions/voice/start',
    voice: (id: number) => `/sessions/${id}/voice`,
  },
  schedule: {
    locations: '/schedule/locations',
    location: (id: number) => `/schedule/locations/${id}`,
    rooms: '/schedule/rooms',
    room: (id: number) => `/schedule/rooms/${id}`,
    classes: '/schedule/classes',
    class: (id: number) => `/schedule/classes/${id}`,
    classMeetings: (id: number) => `/schedule/classes/${id}/meetings`,
    classEnrollments: (id: number) => `/schedule/classes/${id}/enrollments`,
    classWaitlist: (id: number) => `/schedule/classes/${id}/waitlist`,
    joinClass: (id: number) => `/schedule/classes/${id}/join`,
    meetings: '/schedule/meetings',
    meeting: (id: number) => `/schedule/meetings/${id}`,
    closeMeeting: (id: number) => `/schedule/meetings/${id}/close`,
    meetingSummary: (id: number) => `/schedule/meetings/${id}/summary`,
    checkinTokens: (meetingId: number) => `/schedule/meetings/${meetingId}/checkin-tokens`,
    checkIn: (token: string) => `/schedule/check-in/${token}`,
    attendance: (meetingId: number) => `/schedule/meetings/${meetingId}/attendance`,
  },
  certificates: {
    rule: (courseId: number) => `/certificates/rules/${courseId}`,
    eligibility: (courseId: number, studentId: number) => `/certificates/courses/${courseId}/students/${studentId}/eligibility`,
    issue: (courseId: number, studentId: number) => `/certificates/courses/${courseId}/students/${studentId}/issue`,
    courseCertificates: (courseId: number) => `/certificates/courses/${courseId}/certificates`,
    revoke: (id: number) => `/certificates/${id}/revoke`,
    validate: (code: string) => `/certificates/validate/${code}`,
    my: '/certificates/students/me',
    student: (studentId: number) => `/certificates/students/${studentId}`,
  },
  notifications: {
    templates: '/notifications/templates',
    template: (key: string, channel: string) => `/notifications/templates/${key}/${channel}`,
    events: '/notifications/events',
    processDue: '/notifications/events/process-due',
    eventSent: (id: number) => `/notifications/events/${id}/mark-sent`,
    eventFailed: (id: number) => `/notifications/events/${id}/mark-failed`,
  },
  finance: {
    plans: '/finance/plans',
    plan: (id: number) => `/finance/plans/${id}`,
    subscriptions: '/finance/subscriptions',
    subscription: (id: number) => `/finance/subscriptions/${id}`,
    charges: '/finance/charges',
    charge: (id: number) => `/finance/charges/${id}`,
    chargePaid: (id: number) => `/finance/charges/${id}/paid`,
    chargeFailed: (id: number) => `/finance/charges/${id}/failed`,
  },
  analytics: {
    overview: '/analytics/overview',
    courses: '/analytics/courses',
    course: (id: number) => `/analytics/courses/${id}`,
    me: '/analytics/students/me',
    student: (id: number) => `/analytics/students/${id}`,
    class: (id: number) => `/analytics/classes/${id}`,
    reports: {
      completion: '/analytics/reports/completion',
      attendance: '/analytics/reports/attendance',
      engagement: '/analytics/reports/engagement',
      performance: '/analytics/reports/performance',
      roi: '/analytics/reports/roi',
    },
  },
  documents: {
    list: '/documents',
    detail: (id: number) => `/documents/${id}`,
    versions: (id: number) => `/documents/${id}/versions`,
    versionDownload: (documentId: number, versionId: number) => `/documents/${documentId}/versions/${versionId}/download`,
    download: (id: number) => `/documents/${id}/download`,
  },
  forum: {
    courseThreads: (courseId: number) => `/forum/courses/${courseId}/threads`,
    thread: (threadId: number) => `/forum/threads/${threadId}`,
    posts: (threadId: number) => `/forum/threads/${threadId}/posts`,
  },
  chat: {
    conversations: '/chat/conversations',
    conversation: (id: number) => `/chat/conversations/${id}`,
    messages: (id: number) => `/chat/conversations/${id}/messages`,
  },
};
